#!/usr/bin/env python3

# This script downloads the contents of the local cache from a RADOS remote
# storage.

import rados
import struct
import os
import sys

import progress.bar
import progress.spinner
import humanize

config = os.getenv("RADOS_CONF", "ceph.conf")
cluster = rados.Rados(conffile=config)
cluster.connect()
pool = "ccache"  # must exist
ioctx = cluster.open_ioctx(pool)

ccache = os.getenv("CCACHE_DIR", os.path.expanduser("~/.cache/ccache"))

try:
    count = ioctx.get_stats()["num_objects"]
except Exception:
    count = None  # only for showing progress
files = result = manifest = objects = 0
size = 0
columns = os.get_terminal_size()[0]
width = min(columns - 24, 100)
bar = progress.bar.Bar(
    "Downloading...", max=count, fill="=", suffix="%(percent).1f%%", width=width
)
if not count:
    bar = progress.spinner.Spinner("Downloading... ")

for obj in ioctx.list_objects():
    base = obj.key
    val = obj.read()
    if val is None:
        continue
    else:
        objects += 1
        if val[2] == 0 and val[3] == 0:
            ext = "R"
            result += 1
        elif val[2] == 0 and val[3] == 1:
            ext = "M"
            manifest += 1
        else:
            ext = "O"
        filename = os.path.join(ccache, base[0], base[1], base[2:] + ext)
        if not os.path.exists(filename):
            mtime = struct.unpack("!f", obj.get_xattr("mtime"))
            dirname = os.path.join(ccache, base[0], base[1])
            os.makedirs(dirname, mode=0o755, exist_ok=True)
            with open(filename, "wb") as out:
                out.write(val)
            os.utime(filename, (mtime, mtime))
    files += 1
    size += len(val)
    bar.next()
bar.finish()
ioctx.close()

print(
    "%d files, %d result (%d manifest) = %d objects (%s)"
    % (files, result, manifest, objects, humanize.naturalsize(size, binary=True))
)
