#!/usr/bin/env python3

import lmdb
import struct
import os
import sys

import progress.bar

filename = "ccache.mdb"
if len(sys.argv) > 1:
    filename = sys.argv[1]
entry = None
if len(sys.argv) > 2:
    entry = sys.argv[2]
env = lmdb.open(filename, map_size=5 * 1 << 30, subdir=False, max_dbs=2)
base, ext = os.path.splitext(filename)
db2 = env.open_db(b"mtime")
txn = env.begin(write=False)


def extract(key, val):
    mtime = struct.unpack("!f", txn.get(key, db=db2))[0]
    path = base + "/" + (key[0:2] + b"/" + key[2:]).decode("ASCII")
    os.makedirs(os.path.dirname(path), mode=0o755, exist_ok=True)
    with open(path, "wb") as out:
        out.write(val)
    os.utime(path, (mtime, mtime))


if entry:
    key = bytes(entry.replace("/", ""), "ASCII")
    extract(key, txn.get(key))
else:
    count = txn.stat()["entries"]
    columns = os.get_terminal_size()[0]
    width = min(columns - 24, 100)
    bar = progress.bar.Bar(
        "Extracting...", max=count, fill="=", suffix="%(percent).1f%%", width=width
    )
    for key, val in txn.cursor():
        if key != b"mtime":
            extract(key, val)
        bar.next()
    bar.finish()
