#!/usr/bin/env python3

import lmdb
import struct
import os
import sys

import datetime

filename = "ccache.mdb"
if len(sys.argv) > 1:
    filename = sys.argv[1]
env = lmdb.open(filename, map_size=5 * 1 << 30, subdir=False, max_dbs=2)

db2 = env.open_db(b"mtime")
txn = env.begin(write=False)

cursor = txn.cursor()
for key, val in cursor:
    if key == b"mtime":
        continue
    mtime = struct.unpack("!f", txn.get(key, db=db2))[0]
    dt = datetime.datetime.fromtimestamp(mtime)
    ts = dt.strftime("%Y-%m-%d %H:%M")
    print("%15d %s %s" % (len(val), ts, key.decode("ASCII")))
