#!/usr/bin/env python3

# This script uploads the contents of the local cache to a RPC remote storage.

import msgpackrpc
import msgpack
import base64
import binascii
import os

import progress.bar
import humanize

config = os.getenv("RPC_CONF", "localhost")
if ":" in config:
    host, port = config.rsplit(":", 1)
    sock = None
elif config.startswith("/"):
    host, port, sock = None, None, config
else:
    host, port, sock = config, 8080, None
username = os.getenv("RPC_USERNAME")
password = os.getenv("RPC_PASSWORD")
if sock:
    raise NotImplementedError
client = msgpackrpc.Client(msgpackrpc.Address(host, port))
if password:
    client.call("auth", password)

ccache = os.getenv("CCACHE_DIR", os.path.expanduser("~/.cache/ccache"))
filelist = []
for dirpath, dirnames, filenames in os.walk(ccache):
    # sort by modification time, most recently used last
    for filename in filenames:
        if filename.endswith(".lock"):
            continue
        stat = os.stat(os.path.join(dirpath, filename))
        filelist.append((stat.st_mtime, dirpath, filename, stat.st_size))
filelist.sort()

bin32hex = str.maketrans(
    "0123456789abcdefghijklmnopqrstuv", "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"
)


def hex2digest(h: str) -> bytes:
    digest = binascii.unhexlify(bytes(h[0:4], "ASCII"))
    digest += base64.b32decode(bytes(h[4:].translate(bin32hex) + "===", "ASCII"))
    assert len(digest) == 20
    return digest


files = result = manifest = objects = 0
size = 0
columns = os.get_terminal_size()[0]
width = min(columns - 22, 100)
bar = progress.bar.Bar(
    "Uploading...", max=len(filelist), fill="=", suffix="%(percent).1f%%", width=width
)
for mtime, dirpath, filename, filesize in filelist:
    dirname = dirpath.replace(ccache + os.path.sep, "")
    if dirname == "tmp":
        continue
    elif filename == "CACHEDIR.TAG" or filename == "stats":
        # ignore these
        files += 1
    else:
        (base, ext) = filename[:-1], filename[-1:]
        if ext == "R" or ext == "M":
            if ext == "R":
                result += 1
            if ext == "M":
                manifest += 1
            key = "".join(list(os.path.split(dirname)) + [base])
            digest = hex2digest(key)
            val = open(os.path.join(dirpath, filename), "rb").read() or None
            if val:
                # print("%s: %s %d" % (key, ext, len(val)))
                if not client.call("exists", digest):
                    result = client.call("put", digest, val)
                objects += 1
        files += 1
        size += filesize
    bar.next()
bar.finish()

print(
    "%d files, %d result (%d manifest) = %d objects (%s)"
    % (files, result, manifest, objects, humanize.naturalsize(size, binary=True))
)
