#!/usr/bin/env python3

# This script uploads the contents of the local cache
# to an Aerospike remote storage.

import aerospike
import os

import progress.bar
import humanize

config = os.getenv("AEROSPIKE_CONF", "localhost")
if ":" in config:
    host, port = config.rsplit(":", 1)
    sock = None
elif config.startswith("/"):
    host, port, sock = None, None, config
else:
    host, port, sock = config, 3000, None
namespace = os.getenv("AEROSPIKE_NAMESPACE", "test")

username = os.getenv("AEROSPIKE_USERNAME")
password = os.getenv("AEROSPIKE_PASSWORD")
client = aerospike.client(
    {"hosts": [(host, port)], "user": username, "password": password}
)

ccache = os.getenv("CCACHE_DIR", os.path.expanduser("~/.cache/ccache"))
filelist = []
for dirpath, dirnames, filenames in os.walk(ccache, topdown=True):
    # sort by modification time, most recently used last
    for filename in filenames:
        if filename.endswith(".lock"):
            continue
        stat = os.stat(os.path.join(dirpath, filename))
        filelist.append((stat.st_mtime, dirpath, filename, stat.st_size))
    dirnames[:] = [d for d in dirnames if d != "tmp"]
filelist.sort()

files = result = manifest = objects = 0
size = 0
columns = os.get_terminal_size()[0]
width = min(columns - 22, 100)
bar = progress.bar.Bar(
    "Uploading...", max=len(filelist), fill="=", suffix="%(percent).1f%%", width=width
)
for mtime, dirpath, filename, filesize in filelist:
    dirname = dirpath.replace(ccache + os.path.sep, "")
    if filename != "ccache.conf" and filename != "CACHEDIR.TAG" and filename != "stats":
        (base, ext) = filename[:-1], filename[-1:]
        if ext == "R" or ext == "M":
            if ext == "R":
                result += 1
            if ext == "M":
                manifest += 1
            digest = "".join(list(os.path.split(dirname)) + [base])
            key = (namespace, 'redis', digest)
            val = open(os.path.join(dirpath, filename), "rb").read() or None
            if val:
                # print("%s: %s %d" % (key, ext, len(val)))
                #try:
                #    pol = { 'exists': aerospike.POLICY_EXISTS_CREATE }
                #    client.put(key, {'b': val}, policy=pol)
                #except aerospike.exception.RecordExistsError:
                #    pass
                if client.exists(key) == (key, None):
                    client.put(key, {'b': val})
                objects += 1
        files += 1
        size += filesize
    bar.next()
client.close()
bar.finish()

print(
    "%d files, %d result (%d manifest) = %d objects (%s)"
    % (files, result, manifest, objects, humanize.naturalsize(size, binary=True))
)
