language: c

addons:
    apt:
        packages:
            - gperf
            - elfutils
            - zlib1g-dev
            - libmemcached-dev
            - memcached
            - mingw32
            - mingw32-binutils
            - clang    # scan-build

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

matrix:
    include:
        - os: linux
          compiler: gcc
          sudo: required
          dist: trusty
          env: FEATURES="--enable-memcached"
#        - os: linux
#          compiler: i586-mingw32msvc-gcc
#          env: HOST="--host=i586-mingw32msvc" TEST="test/main.exe"
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=undefined" ASAN_OPTIONS="detect_leaks=0"
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=address -g" ASAN_OPTIONS="detect_leaks=0"
        - os: linux
          compiler: clang
          env: PATH="/usr/bin:$PATH" TEST=analyze

    exclude:
        - os: osx
          compiler: gcc

script:
    - ./autogen.sh
    - ./configure $HOST $FEATURES
    - make
    - make ${TEST:-test}
